logging:
  level: INFO
  loggers:
    org.liyanxu: DEBUG

swagger:
  resourcePackage: org.dropwizard.test.resource
template: Hello, %s!
defaultName: Marta

server:
  applicationConnectors:
  - type: http
    port: 8088
  adminConnectors:
  - type: http
    port: 8082
  rootPath: /api/v1/client